from __future__ import annotations

from app.services.domain_types import GeneratedICP, ProductUnderstanding


class ICPGenerationService:
    def generate(self, understanding: ProductUnderstanding) -> list[GeneratedICP]:
        if understanding.subcategory == "Video Streaming":
            return self._video_streaming_profiles()
        if understanding.category == "B2B Software":
            return self._b2b_software_profiles()
        return self._generic_profiles(understanding)

    def _video_streaming_profiles(self) -> list[GeneratedICP]:
        return [
            GeneratedICP(
                name="Price-sensitive solo mobile viewer",
                description="A single viewer using mobile devices who compares entertainment subscriptions closely.",
                use_case="Affordable on-the-go entertainment during commute and short-form downtime.",
                goals=["Keep monthly entertainment spend predictable", "Retain enough content variety", "Watch smoothly on mobile"],
                pain_points=["Price changes trigger plan review", "Too many overlapping subscriptions", "Premium tiers feel overbuilt"],
                decision_drivers=["price_affordability", "content_access", "mobile_experience", "brand_habit", "video_quality"],
                driver_weights={
                    "price_affordability": 0.35,
                    "content_access": 0.25,
                    "mobile_experience": 0.20,
                    "brand_habit": 0.10,
                    "video_quality": 0.10,
                },
                price_sensitivity=0.85,
                switching_cost=0.20,
                alternatives=["YouTube", "Disney+ Hotstar", "Prime Video", "local TV bundles"],
                churn_threshold=-0.18,
                retention_threshold=0.05,
                adoption_friction=0.18,
                value_perception_explanation="This viewer stays when price remains legible and mobile viewing quality feels good enough.",
                segment_weight=0.24,
            ),
            GeneratedICP(
                name="Family entertainment household",
                description="A shared subscription household balancing cost with multi-device usage and kid-safe variety.",
                use_case="Evening and weekend household entertainment across TV and tablets.",
                goals=["Support multiple viewers", "Avoid friction across devices", "Keep enough variety for adults and children"],
                pain_points=["Simultaneous stream limits", "Household downgrade pressure", "Comparing value vs bundled telecom offers"],
                decision_drivers=["content_access", "family_fit", "device_support", "price_affordability", "brand_habit"],
                driver_weights={
                    "content_access": 0.28,
                    "family_fit": 0.24,
                    "device_support": 0.20,
                    "price_affordability": 0.18,
                    "brand_habit": 0.10,
                },
                price_sensitivity=0.62,
                switching_cost=0.42,
                alternatives=["Disney+ Hotstar", "Prime Video", "cable bundles"],
                churn_threshold=-0.20,
                retention_threshold=0.06,
                adoption_friction=0.22,
                value_perception_explanation="Households tolerate moderate price movement if concurrency and family content remain strong.",
                segment_weight=0.27,
            ),
            GeneratedICP(
                name="Premium quality binge watcher",
                description="A heavy viewer who values quality, breadth, and reliable access more than absolute price.",
                use_case="Primary nightly entertainment platform on large-screen devices.",
                goals=["Watch premium originals", "Maintain top-tier quality", "Avoid interruptions across sessions"],
                pain_points=["Feature downgrades feel punitive", "Content removals erode trust", "Too many fragmented exclusives"],
                decision_drivers=["content_access", "video_quality", "brand_habit", "device_support", "price_affordability"],
                driver_weights={
                    "content_access": 0.30,
                    "video_quality": 0.24,
                    "brand_habit": 0.18,
                    "device_support": 0.16,
                    "price_affordability": 0.12,
                },
                price_sensitivity=0.34,
                switching_cost=0.55,
                alternatives=["HBO Max", "Prime Video", "Apple TV+"],
                churn_threshold=-0.23,
                retention_threshold=0.08,
                adoption_friction=0.16,
                value_perception_explanation="Premium viewers accept higher prices if quality and access remain visibly superior.",
                segment_weight=0.19,
            ),
            GeneratedICP(
                name="Multi-subscription household optimizer",
                description="A subscription stack manager who rotates services based on content windows and price promotions.",
                use_case="Switching services every few months to maximize entertainment value.",
                goals=["Optimize entertainment ROI", "Time subscriptions around releases", "Minimize redundant spend"],
                pain_points=["Price hikes accelerate rotation", "Overlapping catalogs reduce stickiness", "Premium tiers require justification"],
                decision_drivers=["price_affordability", "content_access", "value_for_money", "device_support", "brand_habit"],
                driver_weights={
                    "price_affordability": 0.30,
                    "content_access": 0.24,
                    "value_for_money": 0.22,
                    "device_support": 0.14,
                    "brand_habit": 0.10,
                },
                price_sensitivity=0.74,
                switching_cost=0.28,
                alternatives=["Disney+ Hotstar", "Prime Video", "rotating month-to-month bundles"],
                churn_threshold=-0.16,
                retention_threshold=0.04,
                adoption_friction=0.20,
                value_perception_explanation="This optimizer needs visible differentiation or they downgrade first and churn quickly after.",
                segment_weight=0.18,
            ),
            GeneratedICP(
                name="Regional content loyalist",
                description="A viewer focused on culturally relevant titles, dubbed access, and steady mobile/TV usability.",
                use_case="Frequent regional-language viewing for shared family entertainment.",
                goals=["Find relevant language content", "Stream reliably across devices", "Keep service familiar for the household"],
                pain_points=["Thin regional catalog", "Poor recommendation quality", "Price hikes without catalog depth"],
                decision_drivers=["regional_content", "content_access", "price_affordability", "mobile_experience", "brand_habit"],
                driver_weights={
                    "regional_content": 0.30,
                    "content_access": 0.24,
                    "price_affordability": 0.20,
                    "mobile_experience": 0.14,
                    "brand_habit": 0.12,
                },
                price_sensitivity=0.58,
                switching_cost=0.33,
                alternatives=["regional OTT services", "Disney+ Hotstar", "Prime Video"],
                churn_threshold=-0.19,
                retention_threshold=0.05,
                adoption_friction=0.21,
                value_perception_explanation="Regional catalog strength protects retention, but only when the price step-up feels earned.",
                segment_weight=0.12,
            ),
        ]

    def _b2b_software_profiles(self) -> list[GeneratedICP]:
        return [
            GeneratedICP(
                name="Hands-on growth operator",
                description="A builder-owner evaluating ROI tightly and preferring fast setup.",
                use_case="Operational use by one power user owning experimentation and reporting.",
                goals=["Prove measurable ROI quickly", "Reduce manual work", "Avoid expensive shelfware"],
                pain_points=["Slow onboarding", "Opaque pricing", "Weak integrations"],
                decision_drivers=["price_affordability", "automation_coverage", "analytics_depth", "implementation_complexity", "support_reliability"],
                driver_weights={
                    "price_affordability": 0.24,
                    "automation_coverage": 0.25,
                    "analytics_depth": 0.22,
                    "implementation_complexity": 0.17,
                    "support_reliability": 0.12,
                },
                price_sensitivity=0.61,
                switching_cost=0.36,
                alternatives=["manual workflows", "lighter point tools", "internal spreadsheet stack"],
                churn_threshold=-0.18,
                retention_threshold=0.06,
                adoption_friction=0.28,
                value_perception_explanation="This segment keeps products that ship value quickly and stay easy to justify.",
                segment_weight=0.34,
            ),
            GeneratedICP(
                name="Cross-functional team lead",
                description="A manager buying for multi-user adoption, reporting, and consistency.",
                use_case="Shared workflow across product, marketing, and ops stakeholders.",
                goals=["Standardize workflows", "Increase team visibility", "Support decision-making across functions"],
                pain_points=["Seat-based costs spike quickly", "Feature fragmentation", "Admin overhead"],
                decision_drivers=["team_enablement", "analytics_depth", "feature_completeness", "support_reliability", "price_affordability"],
                driver_weights={
                    "team_enablement": 0.26,
                    "analytics_depth": 0.22,
                    "feature_completeness": 0.22,
                    "support_reliability": 0.16,
                    "price_affordability": 0.14,
                },
                price_sensitivity=0.46,
                switching_cost=0.48,
                alternatives=["incumbent suite tools", "BI tools", "PM tooling"],
                churn_threshold=-0.22,
                retention_threshold=0.07,
                adoption_friction=0.31,
                value_perception_explanation="Team leads resist churn when workflow breadth and reporting reliability remain strong.",
                segment_weight=0.38,
            ),
            GeneratedICP(
                name="Finance-aware procurement reviewer",
                description="A secondary stakeholder checking spend, lock-in, and contract structure.",
                use_case="Pricing review before expansion or renewal.",
                goals=["Keep spend efficient", "Reduce vendor overlap", "Preserve negotiation leverage"],
                pain_points=["Opaque packaging", "Overlapping add-ons", "Usage unpredictability"],
                decision_drivers=["price_affordability", "budget_predictability", "feature_completeness", "support_reliability", "implementation_complexity"],
                driver_weights={
                    "price_affordability": 0.28,
                    "budget_predictability": 0.24,
                    "feature_completeness": 0.18,
                    "support_reliability": 0.16,
                    "implementation_complexity": 0.14,
                },
                price_sensitivity=0.67,
                switching_cost=0.26,
                alternatives=["renegotiation", "competitor benchmark tools", "partial rollback"],
                churn_threshold=-0.17,
                retention_threshold=0.04,
                adoption_friction=0.19,
                value_perception_explanation="Procurement reviewers tolerate price only when packaging remains legible and spend predictable.",
                segment_weight=0.28,
            ),
        ]

    def _generic_profiles(self, understanding: ProductUnderstanding) -> list[GeneratedICP]:
        return [
            GeneratedICP(
                name="Value-focused evaluator",
                description="A practical buyer comparing value, ease, and risk before committing.",
                use_case="Initial evaluation of the product against competing options.",
                goals=["Understand whether the product is worth the spend", "Reach value quickly", "Avoid lock-in"],
                pain_points=["Unclear packaging", "Sparse public proof", "Setup uncertainty"],
                decision_drivers=["price_affordability", "feature_completeness", "support_reliability", "implementation_complexity", "brand_habit"],
                driver_weights={
                    "price_affordability": 0.28,
                    "feature_completeness": 0.24,
                    "support_reliability": 0.18,
                    "implementation_complexity": 0.18,
                    "brand_habit": 0.12,
                },
                price_sensitivity=0.58,
                switching_cost=0.30,
                alternatives=["category competitors", "manual alternatives"],
                churn_threshold=-0.18,
                retention_threshold=0.05,
                adoption_friction=0.24,
                value_perception_explanation="This profile retains when the value story stays simple and the adoption path stays short.",
                segment_weight=0.34,
            ),
            GeneratedICP(
                name="Outcome-driven buyer",
                description="A buyer prioritizing measurable outcomes over lowest price.",
                use_case="Deploying the product where business impact matters more than cosmetic features.",
                goals=["Improve a core workflow", "Reduce execution risk", "Gain confidence in results"],
                pain_points=["Weak differentiation", "Poor support", "Feature regressions"],
                decision_drivers=["feature_completeness", "support_reliability", "team_enablement", "price_affordability", "brand_habit"],
                driver_weights={
                    "feature_completeness": 0.28,
                    "support_reliability": 0.22,
                    "team_enablement": 0.20,
                    "price_affordability": 0.16,
                    "brand_habit": 0.14,
                },
                price_sensitivity=0.42,
                switching_cost=0.44,
                alternatives=["incumbents", "custom internal workflows"],
                churn_threshold=-0.21,
                retention_threshold=0.07,
                adoption_friction=0.26,
                value_perception_explanation="This profile keeps products that remain dependable and outcome-aligned, even through moderate price movement.",
                segment_weight=0.33,
            ),
            GeneratedICP(
                name="Budget-constrained skeptic",
                description="A cautious evaluator who needs confidence before paying more.",
                use_case="Reviewing if the product can justify inclusion in a tight budget.",
                goals=["Control spend", "Avoid overbuying", "Keep alternatives open"],
                pain_points=["Over-packaged tiers", "Price jumps", "Weak proof of value"],
                decision_drivers=["price_affordability", "budget_predictability", "feature_completeness", "implementation_complexity", "brand_habit"],
                driver_weights={
                    "price_affordability": 0.34,
                    "budget_predictability": 0.22,
                    "feature_completeness": 0.18,
                    "implementation_complexity": 0.16,
                    "brand_habit": 0.10,
                },
                price_sensitivity=0.72,
                switching_cost=0.18,
                alternatives=["lighter tools", "do nothing", "manual process"],
                churn_threshold=-0.15,
                retention_threshold=0.04,
                adoption_friction=0.20,
                value_perception_explanation="Budget skeptics are the first to downgrade or leave when value becomes ambiguous.",
                segment_weight=0.33,
            ),
        ]
